export const LOAD_ISP_OVERVIEW = 'isp/LOAD_ISP_OVERVIEW';
export const LOAD_ISP_OVERVIEW_SUCCESS = 'isp/LOAD_ISP_OVERVIEW_SUCCESS';
export const SAVE_ISP_OVERVIEW = 'isp/SAVE_ISP_OVERVIEW';
export const SAVE_ISP_OVERVIEW_SUCCESS = 'isp/SAVE_ISP_OVERVIEW_SUCCESS';
export const CHANGE_ISP_OVERVIEW_FORM = 'isp/CHANGE_ISP_OVERVIEW_FORM';
export const CHANGE_ISP_OVERVIEW_FORM_SUCCESS = 'isp/CHANGE_ISP_OVERVIEW_FORM_SUCCESS';
