export const LOAD_POC_PART3 = 'poc/part3manage/LOAD_POC_PART3';
export const LOAD_POC_PART3_SUCCESS = 'poc/part3manage/LOAD_POC_PART3_SUCCESS';
export const LOAD_POC_PART3_ERROR = 'poc/part3manage/LOAD_POC_PART3_ERROR';

export const CREATE_SHARED_PLANNING = 'poc/part3manage/CREATE_SHARED_PLANNING';
export const UPDATE_SHARED_PLANNING = 'poc/part3manage/UPDATE_SHARED_PLANNING';
export const SAVE_SHARED_PLANNING_SUCCESS = 'poc/part3manage/SAVE_SHARED_PLANNING_SUCCESS';
export const SAVE_SHARED_PLANNING_ERROR = 'poc/part3manage/SAVE_SHARED_PLANNING_ERROR';

export const CHANGE_SHARED_PLANNING_FORM = 'poc/part3manage/CHANGE_SHARED_PLANNING_FORM';

export const DELETE_POC_PART3_ITEM = 'poc/part3manage/DELETE_POC_PART3_ITEM';
export const DELETE_POC_PART3_ITEM_SUCCESS = 'poc/part3manage/DELETE_POC_PART3_ITEM_SUCCESS';
export const DELETE_POC_PART3_ITEM_ERROR = 'poc/part3manage/DELETE_POC_PART3_ITEM_ERROR';
export const CANCEL_SHARED_PLANNING_EDIT = 'poc/part3manage/CANCEL_SHARED_PLANNING_EDIT';

export const CHANGE_PLAYGROUND_SHARED_PLANNING = 'poc/part3manage/CHANGE_PLAYGROUND_SHARED_PLANNING';
export const SWITCH_TO_EDIT_MODE = 'poc/part3manage/SWITCH_TO_EDIT_MODE';
export const SWITCH_TO_CREATE_MODE = 'poc/part3manage/SWITCH_TO_CREATE_MODE';

export const SHARED_PLANNING_START_DELETING = 'poc/part3manage/SHARED_PLANNING_START_DELETING';
export const SHARED_PLANNING_DELETING_CONFIRMED = 'poc/part3manage/SHARED_PLANNING_DELETING_CONFIRMED';

export const ADD_SHARED_PLANNING_FORM = 'poc/part3manage/ADD_SHARED_PLANNING_FORM';

export const SAVE_SHARED_PLANNING_FORM = 'poc/part3manage/SAVE_SHARED_PLANNING_FORM';

export const UPDATE_SHARED_PLANNING_DELETE = 'poc/part3manage/UPDATE_SHARED_PLANNING_DELETE';


export const SAVE_SHARED_PLANNINGS = 'poc/part3manage/SAVE_SHARED_PLANNINGS';

export const SAVE_SHARED_PLANNINGS_SUCCESS = 'poc/part3manage/SAVE_SHARED_PLANNINGS_SUCCESS';

export const EDIT_PLAYGROUND_SHARED_PLANNING = 'poc/part3manage/EDIT_PLAYGROUND_SHARED_PLANNING';

//export const LOAD_SHARED_PLANNING_AUDIT_TRIALS = 'poc/part3manage/LOAD_SHARED_PLANNING_AUDIT_TRIALS';
//export const LOAD_SHARED_PLANNING_AUDIT_TRIALS_SUCCESS = 'poc/part3manage/LOAD_SHARED_PLANNING_AUDIT_TRIALS_SUCCESS';

export const FORM_VALIDATED = 'poc/part3manage/FORM_VALIDATED';

