export const LOAD_SERVICE_AND_OUTCOMES = 'isp/planForSupports/LOAD_SERVICE_AND_OUTCOMES';
export const LOAD_SERVICE_AND_OUTCOMES_SUCCESS = 'isp/planForSupports/LOAD_SERVICE_AND_OUTCOMES_SUCCESS';

export const SERVICE_AND_OUTCOMES_UPDATE_FORM = 'isp/planForSupports/SERVICE_AND_OUTCOMES_UPDATE_FORM';

export const SERVICE_AND_OUTCOMES_CHANGE_OUTCOME = 'isp/planForSupports/SERVICE_AND_OUTCOMES_CHANGE_OUTCOME';

export const SAVE_SERVICE_AND_OUTCOMES = 'isp/planForSupports/SAVE_SERVICE_AND_OUTCOMES';
export const SERVICE_AND_OUTCOMES_SAVED = 'isp/planForSupports/SERVICE_AND_OUTCOMES_SAVED';
export const ADD_SERVICE_AND_OUTCOMES = 'isp/planForSupports/ADD_SERVICE_AND_OUTCOMES';
export const DELETE_SERVICE_AND_OUTCOMES = 'isp/planForSupports/DELETE_SERVICE_AND_OUTCOMES';

