export const LOAD_ISP_PART5_SUMMARY = 'isp/planForSupports/LOAD_ISP_PART5_SUMMARY';
export const LOAD_ISP_PART5_SUMMARY_SUCCESS = 'isp/planForSupports/LOAD_ISP_PART5_SUMMARY_SUCCESS';

export const INIT_COMPONENTS_REF_STATE = 'isp/planForSupports/INIT_COMPONENTS_REF_STATE';

export const ADD_GENERAL_SCHEDULE_SUPPORT = 'isp/planForSupports/ADD_GENERAL_SCHEDULE_SUPPORT';
export const EDIT_GENERAL_SCHEDULE_SUPPORT = 'isp/planForSupports/EDIT_GENERAL_SCHEDULE_SUPPORT';
export const DELETE_GENERAL_SCHEDULE_SUPPORT = 'isp/planForSupports/DELETE_GENERAL_SCHEDULE_SUPPORT';
export const ADD_GENERAL_SCHEDULE_SUPPORT_SUCCESS = 'isp/planForSupports/ADD_GENERAL_SCHEDULE_SUPPORT_SUCCESS';
export const EDIT_GENERAL_SCHEDULE_SUPPORT_SUCCESS = 'isp/planForSupports/EDIT_GENERAL_SCHEDULE_SUPPORT_SUCCESS';
export const DELETE_GENERAL_SCHEDULE_SUPPORT_SUCCESS = 'isp/planForSupports/DELETE_GENERAL_SCHEDULE_SUPPORT_SUCCESS';
export const EDIT_GENERAL_SCHEDULE_SUPPORT_COMMENT = 'isp/planForSupports/EDIT_GENERAL_SCHEDULE_SUPPORT_COMMENT';
export const EDIT_GENERAL_SCHEDULE_SUPPORT_COMMENT_SUCCESS = 'isp/planForSupports/EDIT_GENERAL_SCHEDULE_SUPPORT_COMMENT_SUCCESS';

export const TRIGGER_WORKFLOW_EVENT_PLAN_FOR_SUPPORT = 'isp/planForSupports/TRIGGER_WORKFLOW_EVENT_PLAN_FOR_SUPPORT';
export const TRIGGER_WORKFLOW_EVENT_PLAN_FOR_SUPPORT_SUCCESS = 'isp/planForSupports/TRIGGER_WORKFLOW_EVENT_PLAN_FOR_SUPPORT_SUCCESS';

export const REVISE_PLAN_FOR_SUPPORT = 'isp/planForSupports/REVISE_PLAN_FOR_SUPPORT';
export const REVISE_PLAN_FOR_SUPPORT_SUCCESS = 'isp/planForSupports/REVISE_PLAN_FOR_SUPPORT_SUCCESS';
