export const LOAD_PRE_CREATE_MODEL = 'create/LOAD_PRE_CREATE_MODEL';
export const PRE_CREATE_MODEL_LOAD_SUCCESS = "create/PRE_CREATE_MODEL_LOAD_SUCCESS";

export const SAVE_MODEL = 'create/SAVE_MODEL';
export const SAVE_MODEL_SUCCESS = 'create/SAVE_MODEL_SUCCESS';

export const UPDATE_FORM = 'create/UPDATE_FORM';
export const UPDATE_FORM_SUCCESS = 'create/UPDATE_FORM_SUCCESS';

export const INIT_COMPONENTS_REF_STATE = 'create/INIT_COMPONENTS_REF_STATE';
export const REFRESH_COMPONENTS_REF_STATE = 'create/REFRESH_COMPONENTS_REF_STATE';

export const UPDATE_VALIDATION_LIST = 'section/UPDATE_VALIDATION_LIST';
export const CLEAR_VALIDATION_LIST = 'section/CLEAR_VALIDATION_LIST';

export const INIT_CREATE_DATA = 'section/INIT_CREATE_DATA';