export const LOAD_POC_PART3 = 'poc/part3manage/LOAD_POC_PART3';
export const LOAD_POC_PART3_SUCCESS = 'poc/part3manage/LOAD_POC_PART3_SUCCESS';
export const EDIT_PLAYGROUND_SHARED_PLANNING = 'poc/part3manage/EDIT_PLAYGROUND_SHARED_PLANNING';
export const CHANGE_PLAYGROUND_SHARED_PLANNING = 'poc/part3manage/CHANGE_PLAYGROUND_SHARED_PLANNING';


