export const LOAD_POC_Part5 = 'poc/Part5manage/LOAD_POC_Part5';
export const LOAD_POC_Part5_SUCCESS = 'poc/Part5manage/LOAD_POC_Part5_SUCCESS';
export const LOAD_POC_Part5_ERROR = 'poc/Part5manage/LOAD_POC_Part5_ERROR';

export const DELETE_POC_Part5_ITEM_SUCCESS = 'poc/Part5manage/DELETE_POC_Part5_ITEM_SUCCESS';
export const DELETE_POC_Part5_ITEM_ERROR = 'poc/Part5manage/DELETE_POC_Part5_ITEM_ERROR';


export const SAVE_SERVICES = 'poc/Part5manage/SAVE_SERVICES';

export const SAVE_SERVICES_SUCCESS = 'poc/Part5manage/SAVE_SERVICES_SUCCESS';
 
export const ADD_POC_PATIENTSERVICES_FORM = 'poc/Part5manage/ADD_POC_PATIENTSERVICES_FORM';
export const ADD_POC_OUTPATIENTSERVICES_FORM = 'poc/Part5manage/ADD_POC_OUTPATIENTSERVICES_FORM';

export const CHANGE_INPATIENTSERVICES_FORM = 'poc/Part5manage/CHANGE_INPATIENTSERVICES_FORM';
export const CHANGE_OUTPATIENTSERVICES_FORM = 'poc/Part5manage/CHANGE_OUTPATIENTSERVICES_FORM';

export const DELETE_INPATIENT = 'poc/Part5manage/DELETE_INPATIENT';
export const DELETE_OUTPATIENT = 'poc/Part5manage/DELETE_OUTPATIENT';

export const EDIT_INOUTPATIENTSERVICES = 'poc/Part5manage/EDIT_INOUTPATIENTSERVICES';
export const EDIT_OUTPATIENTSERVICES = 'poc/Part5manage/EDIT_OUTPATIENTSERVICES';

export const SWITCH_TO_INPATIENTEDIT_MODE = 'poc/Part5manage/SWITCH_TO_INPATIENTEDIT_MODE';
export const SWITCH_TO_INPATIENTCREATE_MODE = 'poc/Part5manage/SWITCH_TO_INPATIENTCREATE_MODE';
export const SWITCH_TO_OUTPATIENTEDIT_MODE = 'poc/Part5manage/SWITCH_TO_OUTPATIENTEDIT_MODE';
export const SWITCH_TO_OUTPATIENTCREATE_MODE = 'poc/Part5manage/SWITCH_TO_OUTPATIENTCREATE_MODE';
export const SAVE_INPATIENT_FORM = 'poc/Part5manage/SAVE_INPATIENT_FORM';
export const SAVE_OUTPATIENT_FORM = 'poc/Part5manage/SAVE_OUTPATIENT_FORM';

export const FORM_VALIDATED = 'poc/Part5manage/FORM_VALIDATED';

export const LOAD_PROVIDER_SEARCH_CRITERIA_DATA='provider/LOAD_PROVIDER_SEARCH_CRITERIA_DATA';
export const LOAD_PROVIDER_SEARCH_CRITERIA_DATA_SUCCESS='provider/LOAD_PROVIDER_SEARCH_RESULT_SUCCESS';

export const SEARCH_PROVIDERS='provider/SEARCH_PROVIDERS';
export const SEARCH_PROVIDERS_SUCCESS='provider/SEARCH_PROVIDERS_SUCCESS';

export const PROVIDER_SELECTED='prodiver/PROVIDER_SELECTED';
export const PROVIDER_SELECTED_SUCCESS='prodiver/PROVIDER_SELECTED_SUCCESS';

export const TREATMENT_TYPE_OUTPATIENT='treatmentType/OUTPATIENT';
export const TREATMENT_TYPE_INPATIENT='treatmentType/INPATIENT';
export const TREATMENT_TYPE_DEFAULT='treatmentType/DEFAULT';

export const CANCEL_INT_OUT_PATIENT='poc/Part5manage/CANCEL_INT_OUT_PATIENT';

export const OUTPATIENT_START_DELETING = 'poc/Part5manage/OUTPATIENT_START_DELETING';
export const INPATIENT_START_DELETING = 'poc/Part5manage/INPATIENT_START_DELETING';

export const ADD_TEMPORARY_PROVIDER = 'poc/Part5manage/ADD_TEMPORARY_PROVIDER';
export const ADD_TEMPORARY_PROVIDER_SUCCESS='poc/Part5manage/ADD_TEMPORARY_PROVIDER_SUCCESS';
export const REMOVE_TEMPORARY_PROVIDER='poc/Part5manage/REMOVE_TEMPORARY_PROVIDER';